### ISSUE TITLE
Circle build should update public docker image

### ISSUE THREAD

**Issue by rossf7** [giantswarm/certctl#53]
We have a public docker image for certctl but its manually updated.

https://hub.docker.com/r/giantswarm/certctl/

The Circle build only pushes to our private registry it would be useful if it pushes to both.

**Comment by JosephSalisbury** [comment]
Correct behaviour here would be pushing to quay, and we have certctl public

**Comment by JosephSalisbury** [comment]
Closing, will be subsumed by https://github.com/giantswarm/giantswarm/issues/1087
