### ISSUE TITLE
certctl issue ignores allow_bare_domain flag

### ISSUE THREAD

**Issue by r7vme** [giantswarm/certctl#75]
certctl creates few roles on the fly. role-<cluster id> and role-org-<has based on org name>. My particular problem was when i was trying to issue certificate with "organization" field. It failed because role created by certctl did not have proper permissions. In particular, i can not set `allow_bare_domain` via `certctl issue`, which is required if you want to use domains like "kubernetes". 

AllowBareDomains is not [passed further](https://github.com/giantswarm/certctl/blob/b8074296d25d1c907bafed843411413fbcdbfff3/cli/issue.go#L76).

**Comment by xh3b4sd** [comment]
@corest wants to check it out and we talk and see what we can do here.

**Comment by corest** [comment]
Fixed
